version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "15672:15672"
      - "5672:5672"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  eureka-service:
    image: eureka-server
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    ports:
      - "8888:8888"
    restart: always
  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    restart: always
  series-service:
    image: series-service
    ports:
      - "8086:8086"
    restart: always
  movie-service:
    image: movie-service
    ports:
      - "8082:8082"
    restart: always
  catalog-service:
    image: catalog-service
    ports:
      - "8084:8084"
    restart: always
  mongodb:
    image: mongo
    container_name: "mongodb"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root1234
      - MONGO_INITDB_ROOT_PASSWORD=root1234
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root1234
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root1234
      - ME_CONFIG_MONGODB_SERVER=mongodb
  mysql:
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_DATABASE=final_back_II
      - MYSQL_USER=hola
      - MYSQL_PASSWORD=chau
      - MYSQL_ROOT_PASSWORD=chau

volumes:
  data: { }
networks:
  default:
    name: mongodb_network
