server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root1234
      password: root1234
      database: final_back_II
      port: 27017
      host: mongodb

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Series Microservice
